image: python:3.6

pages:
  before_script:
    - apt-get update && apt-get install -y gcc g++ make python-dev libpcap-dev
    - python3 setup.py develop
    - pip3 install -e .[docs]
  script:
    - make -C doc-sphinx html && mkdir public && cp -r doc-sphinx/_build/html/* public
  artifacts:
    paths:
    - public
  # only:
  # - master
