# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blip_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blip_record.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x62lip_record.proto\"\x9c\x01\n\nBlipRecord\x12\r\n\x05Magic\x18\x01 \x01(\t\x12\x10\n\x08\x45xchange\x18\x02 \x01(\r\x12\x0e\n\x06Length\x18\x03 \x01(\r\x12%\n\x04Type\x18\x04 \x01(\x0e\x32\x17.BlipRecord.PayloadType\x12\x0f\n\x07Payload\x18\x05 \x01(\x0c\"%\n\x0bPayloadType\x12\x08\n\x04JSON\x10\x00\x12\x0c\n\x08PROTOBUF\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BLIPRECORD_PAYLOADTYPE = _descriptor.EnumDescriptor(
  name='PayloadType',
  full_name='BlipRecord.PayloadType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JSON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTOBUF', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=141,
  serialized_end=178,
)
_sym_db.RegisterEnumDescriptor(_BLIPRECORD_PAYLOADTYPE)


_BLIPRECORD = _descriptor.Descriptor(
  name='BlipRecord',
  full_name='BlipRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Magic', full_name='BlipRecord.Magic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Exchange', full_name='BlipRecord.Exchange', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Length', full_name='BlipRecord.Length', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Type', full_name='BlipRecord.Type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Payload', full_name='BlipRecord.Payload', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BLIPRECORD_PAYLOADTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=178,
)

_BLIPRECORD.fields_by_name['Type'].enum_type = _BLIPRECORD_PAYLOADTYPE
_BLIPRECORD_PAYLOADTYPE.containing_type = _BLIPRECORD
DESCRIPTOR.message_types_by_name['BlipRecord'] = _BLIPRECORD

BlipRecord = _reflection.GeneratedProtocolMessageType('BlipRecord', (_message.Message,), dict(
  DESCRIPTOR = _BLIPRECORD,
  __module__ = 'blip_record_pb2'
  # @@protoc_insertion_point(class_scope:BlipRecord)
  ))
_sym_db.RegisterMessage(BlipRecord)


# @@protoc_insertion_point(module_scope)
